import{S as d,i as m}from"./assets/vendor-9310f15c.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const c={loader:document.querySelector(".loader"),searchBtn:document.querySelector(".search-btn")};function i(s=!0){c.loader.style.display=s?"inline-block":"none",c.searchBtn.disabled=s}const p="https://pixabay.com/api/",y="41899926-74a7536d4d492e936dbb67b5b";function h(s){return i(!0),fetch(s).then(t=>{if(!t.ok)throw new Error(t.ststusText);return t.json()})}function g(s){return s.map(({webformatURL:t,largeImageURL:n,tags:o,likes:e,views:r,comments:a,downloads:f})=>`
          <li class="gallery-item">
    <a class="gallery-link" href="${n}">
      <img
        class="gallery-image"
        src="${t}"
        alt="${o}"
      />
      <p class="gallery-descr">Likes: <span class="descr-span">${e}</span> Views: <span class="descr-span">${r}</span> Comments: <span class="descr-span">${a}</span> Downloads: <span class="descr-span">${f}</span></p>
    </a>
  </li>`).join("")}const b=new d(".gallery-item a",{captionsData:"alt",captionDelay:250}),l={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),gallery:document.querySelector(".gallery")};l.form.addEventListener("submit",s=>{s.preventDefault();const t=l.form.query.value.trim();if(l.gallery.innerHTML="",!t){u("The search field can't be empty! Please, enter your request!");return}const n=`${p}?key=${y}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`;h(n).then(o=>{o.hits.length===0&&(u("Sorry, there are no images matching your search query. Please, try again!"),i(!1)),l.gallery.innerHTML=g(o.hits),i(!1),b.refresh(),l.form.reset()}).catch(o=>console.error(o))});function u(s){m.show({class:"error-svg",position:"topRight",icon:"error-svg",message:s,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers.js.map
